### ISSUE TITLE
Passing linear arguments to non-linear positions?

### ISSUE THREAD

**Issue by clayrat** [jyp/organ#1] opened 2018-02-22 14:09 UTC
In `Organ-HaskeLL.lhs` there seem to be a few places where a function expecting a non-linear argument is passed a linear one, which seems wrong. 

E.g., in https://github.com/jyp/organ/blob/master/Organ-HaskeLL.lhs#L502 `cons` calls `yield` and passes to it a linear `a`, which could potentially be discarded when the second argument is `Full`. 

Another more subtle instance of this is in https://github.com/jyp/organ/blob/master/Organ-HaskeLL.lhs#L567 when a linear lambda obtained from `appendSnk' s2` is passed to `flipSnk` which expects a regular lambda.

**Comment by jyp** [comment] 2018-02-22 18:09
Thanks for pointing these mistakes!

In general the linear haskell compiler is not quite ready to typecheck this file, so I've been doing manual verifications --- thus I am expecting a few mistakes of this sort.

(@aspiwack : perhaps the prototype has improved to the point where we can check this file?)

**Comment by clayrat** [comment] 2018-02-22 18:19
I've stumbled upon this while doing a port to Idris, which has recently added support for linear types:
https://github.com/clayrat/idris-linear/blob/master/src/Streams.idr

**Comment by clayrat** [comment] 2018-02-22 19:10
@jyp The fix seems to still rely on discarding the element in `full'`, so now I'm confused about the definition of `Source.Cons` - it seems to have linear `a` in https://jyp.github.io/pdf/Organ-HaskeLL.pdf, but is defined with a non-linear one in the actual code?

**Comment by clayrat** [comment] 2018-02-22 19:32
The non-linear definition seems to break `yield`, `nnIntro'` and `forwardThenSnk'`. We could also take a middle ground and define `Cons :: a -> N (Sink a) -o Source a` - in this case only `nnIntro'` seems to break.

**Comment by jyp** [comment] 2018-02-22 19:37
Cons is supposed to be linear. The problem is that GHC does not accept newtype arrows in data definitions, so I must use the non-linear arrow in the actual source code.

**Comment by jyp** [comment] 2018-02-22 19:52
regarding flipSnk. Indeed there is an issue here. Perhaps it require writing a version working on Snk instead of Snk'.

**Comment by jyp** [comment] 2018-02-22 20:41
I think it's fixed in my latest commit.

**Closed as completed** 2018-02-22 20:41 UTC

**Comment by clayrat** [comment] 2018-02-22 22:05
Thanks! However it looks like I found some more mistakes. I think I'll finish porting entire section 4 first and post my findings in another issue, to not disturb you too frequently.

**Comment by jyp** [comment] 2018-02-23 07:09
Nice!

Let's hope that my internal linearity-checker did not slip to many mistakes
:)
